/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignCompareRouteImport } from './routes/design-compare'
import { Route as ApiCompareRouteImport } from './routes/api/compare'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignCompareRoute = DesignCompareRouteImport.update({
  id: '/design-compare',
  path: '/design-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompareRoute = ApiCompareRouteImport.update({
  id: '/api/compare',
  path: '/api/compare',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-compare': typeof DesignCompareRoute
  '/api/compare': typeof ApiCompareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-compare': typeof DesignCompareRoute
  '/api/compare': typeof ApiCompareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-compare': typeof DesignCompareRoute
  '/api/compare': typeof ApiCompareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/design-compare' | '/api/compare'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/design-compare' | '/api/compare'
  id: '__root__' | '/' | '/design-compare' | '/api/compare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignCompareRoute: typeof DesignCompareRoute
  ApiCompareRoute: typeof ApiCompareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-compare': {
      id: '/design-compare'
      path: '/design-compare'
      fullPath: '/design-compare'
      preLoaderRoute: typeof DesignCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compare': {
      id: '/api/compare'
      path: '/api/compare'
      fullPath: '/api/compare'
      preLoaderRoute: typeof ApiCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignCompareRoute: DesignCompareRoute,
  ApiCompareRoute: ApiCompareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
